stages:
  generate_data:
    cmd: python src/data_generation.py
    deps:
      - src/data_generation.py
    outs:
      - data/raw/house_prices.csv

  preprocess_data:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/house_prices.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train_model:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train.csv
    outs:
      - models/model.pkl

  evaluate_model:
    cmd: python src/evaluation.py
    deps:
      - src/evaluation.py
      - models/model.pkl
      - data/processed/test.csv
    metrics:
      - metrics.json:
          cache: false